# RUN apt-get -y update && apt-get install -y curl gnupg
# RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
# RUN apt-get install -y nodejs
# RUN npm install npm@latest -g
FROM node:10

WORKDIR /work
